name: videomitra
description: "A CapCut-style Flutter video editor with functional editing and export tools."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  video_player: ^2.9.2
  ffmpeg_kit_flutter_new_video: ^2.5.2
  path_provider: ^2.1.5
  file_picker: ^8.1.7
  share_plus: ^10.1.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
